services:
  - type: web
    name: campusiq-server
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: EMBEDDING_PROVIDER
        value: gemini
      - key: VECTOR_INDEX_NAME
        value: college_documents_vector_index
